apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: forecast-experience
  name: wf-exp-bff-kustomization

resources:
  - deployment.yaml
  - high-availability/hpa.yaml
  - high-availability/pdb.yaml
  - services/service.yaml
  - services/virtual-service.yaml
  - database