apiVersion: v1
kind: Service
metadata:
  name: master-data-svc
  namespace: master-data
spec:
  selector:
    app: master-data
  ports:
    - port: 8080
  sessionAffinity: ClientIP
  # default is None (pure random)
  # ClientIP means: same client IP always goes to same pod
  # kube-proxy tracks this via an iptables recent module
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours, default