FROM flyway/flyway:11.20.3

# Copy migrations into the expected Flyway directory
COPY data/migrations /flyway/sql

# Default command (can be overridden by Job args)
ENTRYPOINT ["flyway"]
CMD ["migrate"]