apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
type: Opaque
stringData:
  grafana-admin-user: admin
  grafana-admin-password: vumxex-Waskod-fyrwu1
  GF_POSTGRES_USER: grafana
  GF_POSTGRES_PASSWORD: jahxeh-qUpwyx-7nokfy
  GF_POSTGRES_DB: grafana
  postgres-user: grafana
  postgres-password: jahxeh-qUpwyx-7nokfy
  postgres-db: grafana
  username: grafana
  password: jahxeh-qUpwyx-7nokfy
  database: grafana