<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain\WeatherInsights.Collector.Domain.csproj" />
      <ProjectReference Include="..\Infrastructure\WeatherInsights.Collector.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MasterData.Client" Version="0.0.1" />
    </ItemGroup>

</Project>
