apiVersion: v1
kind: ConfigMap
metadata:
  name: master-data-service-configmap
  namespace: master-data-service
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "MaximumCitiesBeforeWarning": 300,
      "ConnectionStrings": {
        "Postgres": ""
      }
    }