apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../../../manifests/operations
  - ../_global

namespace: operations

# adds a metadata.label for every resource created by this kustomize hop
# this allows easy resource managemnt using -l filters
commonLabels:
  environment: dev
  domain: operations