services:  
  cities-import:
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile.cities-initializer
    environment:
      - POSTGRES_DSN=postgresql://app_user:app_password@masterdata-postgres:5432/master_data?sslmode=disable
    volumes:
      # mount the local file in the image and mark it as read only
      - ./data/imports:/data:ro
    networks:
      - weatherly-network
    command: ["--input", "/data/capitals.csv"]
    # the init script needs to be ran once
    restart: "no"
  wf-actuals-import:
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile.wf-actuals-initializer
    environment:
      - POSTGRES_DSN=postgresql://app_user:app_password@masterdata-postgres:5432/master_data?sslmode=disable
    volumes:
      - ./data/imports:/data:ro
    networks:
      - weatherly-network
    command: ["--input", "/data/weather_hourly-full.csv"]
    restart: "no"
  wf-actuals-range-db-import:
    profiles:
      - manual
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile.wf-actuals-range
    environment:
      - POSTGRES_DSN=postgresql://app_user:app_password@masterdata-postgres:5432/master_data?sslmode=disable
    networks:
      - weatherly-network
    command:
      - "--from-date"
      - "${FROM_DATE:-2026-01-01}"
      - "--to-date"
      - "${TO_DATE:-2026-01-02}"
    restart: "no"

# necessary for postgres persistence
volumes:
  postgres-data:

networks:
  weatherly-network:
    external: true
    name: weatherly-network