apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-operations-app
  namespace: argocd
  labels:
    workload: operations
    environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/WellArchitectedLabs/WellArchitectedLab.MonoRepo.git
    targetRevision: feature/k8sfullStack
    path: k8s/overlays/weatherly/operations/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s