apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: master-data-service-hpa
  namespace: master-data
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: master-data-service
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70