apiVersion: v1 
kind: Secret 
metadata: 
  name: master-data-db-sealed-secrets 
  namespace: backend 
type: Opaque 
stringData: 
  POSTGRES_SUPERUSER_PASSWORD: supersecret
  DB_APP_USER: masterdata_app 
  DB_APP_PASSWORD: appsecret
  DB_APP_DSN: postgresql://masterdata_app:appsecret@master-data-database-postgresql.backend.svc.cluster.local:5432/master_data