apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: wf-exp-frontend-virtualservice
  namespace: istio-gateway
  labels:
    app: weatherly
    version: v1
spec:
  hosts:
    - front.weatherly.local
  gateways:
    - istio-gateway/weatherly-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: wf-exp-frontend-service.forecast-experience.svc.cluster.local
            port:
              number: 80