apiVersion: batch/v1
kind: CronJob
metadata:
  name: wf-actuals-import
  namespace: backend
  labels:
    app: wf-actuals-import
spec:
  # This cron job is never executed and suspended by default
  # This technique is used in order to simulate a manually applied job
  # With having the argocd sync capabilities
  schedule: "0 0 31 2 *"  # Feb 31st (never runs automatically)
  suspend: true            # Suspended by default - only manual triggers
  jobTemplate:
    spec:
      backoffLimit: 0     # Number of pods retried, here we set to this to zero in order to never retry (default is 6)
      completions: 1      # Job completes after 1 successful pod
      parallelism: 1      # Run 1 pod at a time
      template:
        metadata:
          name: wf-actuals-import
          labels:
            app: wf-actuals-import
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
          tolerations:
          - key: workload
            operator: 'Equal'
            value: 'weather-forecast'
            effect: 'NoSchedule'
          nodeSelector:
            kubernetes.azure.com/mode: user
          initContainers:
          - name: postgres-sanity-guard
            image: acrdevtshpwn.azurecr.io/postgres-sanity-guard:0.1.0-staging-scripts.1-276fa6a
            env:
              - name: DB_HOST
                value: dev-master-data-database-postgresql.backend.svc.cluster.local
              - name: DB_PORT
                value: "5432"
              - name: DB_NAME
                value: master_data
              - name: DB_APP_USER
                valueFrom:
                  secretKeyRef:
                    name: dev-master-data-db-sealed-secrets
                    key: DB_APP_USER
              - name: DB_APP_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: dev-master-data-db-sealed-secrets
                    key: DB_APP_PASSWORD
              - name: POSTGRES_SUPERUSER_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: dev-master-data-db-sealed-secrets
                    key: POSTGRES_SUPERUSER_PASSWORD
              - name: MAX_RETRIES
                value: "30"
              - name: RETRY_INTERVAL
                value: "2"
          containers:
          - name: wf-actuals-import
            image: acrdevtshpwn.azurecr.io/wf-actuals-import:0.1.0-staging-scripts.1-cd835b2
            args: ["--input", "/mnt/blob/weather_hourly-full.csv", "--export-to-postgres"]
            env:
              - name: POSTGRES_DSN
                valueFrom:
                  secretKeyRef:
                    name: dev-master-data-db-sealed-secrets
                    key: DB_APP_DSN
            volumeMounts:
            - name: imports-blob
              mountPath: "/mnt/blob"
          
          volumes:
          - name: imports-blob
            persistentVolumeClaim:
              claimName: dev-pvc-az-blob-imports
          
          restartPolicy: Never