apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny-all.yaml
  - allow-egress-dns.yaml
  - allow-egress-same-namespace.yaml
  - allow-egress-internet.yaml
  - allow-ingress-same-namespace.yaml