apiVersion: v1
kind: Service
metadata:
  name: master-data-service-service
  namespace: master-data
spec:
  selector:
    app: master-data-service
    version: v1
  ports:
  - name: http
    port: 8080
    targetPort: 80