# syntax=docker/dockerfile:1.6

############################
# Stage 1 — Build
############################
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Install jq (only in build stage)
RUN apt-get update \
    && apt-get install -y --no-install-recommends jq \
    && rm -rf /var/lib/apt/lists/*

COPY . .

WORKDIR /src/Presentation

# Restore using BuildKit secret
RUN --mount=type=secret,id=dev_secrets \
    set -e; \
    SECRET_FILE="/run/secrets/dev_secrets"; \
    \
    GITHUB_USERNAME=$(jq -r '.github.username' "$SECRET_FILE"); \
    GITHUB_TOKEN=$(jq -r '.github.token' "$SECRET_FILE"); \
    \
    dotnet nuget add source \
        --username "$GITHUB_USERNAME" \
        --password "$GITHUB_TOKEN" \
        --store-password-in-clear-text \
        --name github \
        "https://nuget.pkg.github.com/WellArchitectedLabs/index.json"; \
    \
    dotnet restore; \
    \
    dotnet nuget remove source github

RUN dotnet publish -c Release -o /app --no-restore

############################
# Stage 2 — Runtime
############################
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

COPY --from=build /app .

EXPOSE 80
ENV ASPNETCORE_URLS=http://+:80

ENTRYPOINT ["dotnet", "WfInsights.Collector.Api.dll"]