<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Domain\WeatherInsights.Bff.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>WeatherInsights.Bff.Application</AssemblyName>
    <RootNamespace>WeatherInsights.Bff.Application</RootNamespace>
  </PropertyGroup>

</Project>
