apiVersion: v1
kind: ConfigMap
metadata:
  name: wf-exp-bff-configmap
  namespace: forecast-experience
data:
  appsettings.json: |
    {
    "Logging": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft.AspNetCore": "Warning"
      }
    },
    "AllowedHosts": "*",
    "WeatherForecast": {
        "Redis": {
          "WriteDbConnection": "dev-wf-exp-bff-redis-primary.forecast-experience.svc.cluster.local:6379",
          "ReadDbConnection": "wf-exp-bff-redis-secondary.forecast-experience.svc.cluster.local:6379"
        }
      }
    }