apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: argocd
  name: bootstrap-kustomization
resources:
  - grafana
  - istio
  - kiali
  - kube
  - loki
  - open-telemetry
  - prometheus
  - tempo
  - namespace.yaml