class ForecastSettings:
    PROPHET_DAILY_SEASONALITY = True
    PROPHET_WEEKLY_SEASONALITY = True
    PROPHET_YEARLY_SEASONALITY = True

    NEAR_HISTORY_WEIGHT = 0.7
    FAR_HISTORY_WEIGHT = 0.3

    FORECAST_HORIZON_HOURS = 24
