services:
  insights-bff:
    build:
      context: ./
      dockerfile: Dockerfile.insights-bff
      secrets:
        - dev_secrets
    container_name: insights-bff
    ports: 
      - 83:80
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      InsightsCollector__Url: "http://insights-collector:80"
      MasterData__Url: "http://master-data-service:80"

secrets:
  dev_secrets:
    file: ~/.wellarchitectedlabs/secrets.json