<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.12.39" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\WeatherForecast.Domain.csproj" />
    <ProjectReference Include="..\Application\WeatherForecast.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\WeatherForecast.Infrastructure.csproj" />
  </ItemGroup>

</Project>
