apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: argocd
  name: kiali-bootstrap-kustomization
resources:
  - blob-csv-driver.yaml
  - sealed-secrets-controller.yaml