apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-az-blob-imports
  namespace: backend
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: blob.csi.azure.com
    volumeHandle: stwfimportsdev_imports
    volumeAttributes:
      storageAccount: stwfimportsdev
      containerName: imports
      resourceGroup: rg-kubernetes-dev-001
      protocol: fuse