services:
  forecast-frontend:
    build:
      context: ./
      dockerfile: Dockerfile.insights-frontend
    environment:
      # Point frontend to backend container
      BACKEND_URL: "http://insights-bff:80"
    container_name: insights-frontend
    ports:
      - "8080:80"
    restart: always